openapi: 3.0.1
info:
  title: BC Zombie Apocalypse
  description: Apocalypse Now!
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://bc-apocalypsis.swagger.io/v2
tags:
- name: Scenario
  description: Simulation scenarios for the apocalypse
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /scenario:
    post:
      tags:
      - Scenario
      summary: Creates a new simulation Scenario
      operationId: createScenario
      requestBody:
        description: Scenario to be stored
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateScenarioRequest'
        required: true
      responses:
        201:
          description: Created Scenario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scenario'
        400:
          description: Client Error (implement freely)
        500:
          description: Server Error (implement freely)
  /scenario/{id}:
    get:
      tags:
      - Scenario
      summary: Get an existing Scenario
      operationId: getScenario
      parameters:
      - name: id
        in: path
        description: ID of Scenario to get
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Scenario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scenario'
        404:
          description: Scenario not found (implement freely)
        500:
          description: Server Error (implement freely)
    put:
      tags:
      - Scenario
      summary: Run an existing Scenario
      operationId: runScenario
      parameters:
      - name: id
        in: path
        description: ID of Scenario to run
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        description: Request for running a Scenario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunScenarioRequest'
        required: true
      responses:
        200:
          description: Scenario after run
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scenario'
              example:
                id: 45
                time: 5
                status: completed
                people:
                  - name: 'Jeff'
                    x: 1
                    y: -1
                    status: zombie
                    items:
                      - class: gun
                        ammo: 2
                      - class: knife
                  - name: 'Fede'
                    x: 1
                    y: 2
                    status: zombie
                  - name: 'Bellini'
                    x: 1
                    y: 0
                    status: dead
                  - name: 'Peluca'
                    x: 1
                    y: -1
                    status: zombie
                    items:
                      - class: gun
                        ammo: 2
        404:
          description: Scenario not found (implement freely)
        400:
          description: Client Error (implement freely)
        409:
          description: Already completed (implement freely)
        500:
          description: Server Error (implement freely)
  /scenario/{id}/logs:
    get:
      tags:
      - Scenario
      summary: Get execution logs for a completed Scenario
      operationId: getLogs
      parameters:
      - name: id
        in: path
        description: ID of Scenario
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Logs for Scenario
          content: 
            application/json:
              example:
                logs:
                  - 'Simulation 45 started...'
                  - '(time = 1) Jeff moved to [3,2]'
                  - '(time = 1) Fede moved to [0,4]'
                  - '(time = 1) Bellini moved to [2,2]'
                  - '(time = 1) Peluca moved to [1,-1]'
                  - '(time = 2) Jeff moved to [2,1]'
                  - '(time = 2) Fede moved to [1,3]'
                  - '(time = 2) Bellini moved to [2,1]'
                  - '(time = 2) Bellini bit Jeff'
                  - '(time = 2) Jeff turned into a zombie'
                  - '(time = 2) Peluca stood still'
                  - '(time = 3) Jeff moved to [1,0]'
                  - '(time = 3) Fede moved to [1,2]'
                  - '(time = 3) Bellini moved to [1,0]'
                  - '(time = 3) Peluca blew Bellinis head off with the gun'
                  - '(time = 3) Bellini rests in pieces'
                  - '(time = 4) Jeff moved to [1,-1]'
                  - '(time = 4) Jeff bit Peluca'
                  - '(time = 4) Peluca turned into a zombie'
                  - '(time = 4) Fede stood still'
                  - '(time = 4) Peluca stood still'
                  - '(time = 5) Jeff stood still'
                  - '(time = 5) Fede stood still'
                  - '(time = 5) Peluca stood still'                  
                  - 'Simulation 45 has been completed...'
                  - 'The human race is doomed'
        404:
          description: Scenario or Logs not found (implement freely)
        500:
          description: Server Error (implement freely)
components:
  schemas:
    Item:
      oneOf:
        - $ref: '#/components/schemas/Gun'
        - $ref: '#/components/schemas/Knife'
    Gun:
      required:
      - class
      - ammo
      properties:
        class:
          type: string
          enum:
            - gun
        ammo:
          type: integer
          description: Bullets remaining
          format: int32
      example:
        class: gun
        ammo: 5
    Knife:
      required:
      - class
      properties:
       class:
        type: string
        enum:
          - knife
      example:
        class: knife
    Person:
      required:
      - name
      - status
      - x
      - y
      type: object
      properties:
        name:
          type: string
        x:
          type: integer
          description: Horizontal position
          format: int32
        y:
          type: integer
          description: Vertical position
          format: int32
        status:
          type: string
          enum:
          - alive
          - zombie
          - dead
        items:
          type: array
          description: Inventory, it may contain any number of items (guns, knives,
            etc...)
          items:
            $ref: '#/components/schemas/Item'
      example:
        name: 'Jeff'
        x: 4
        y: 3
        status: alive
        items:
          - class: gun
            ammo: 2
          - class: knife
    Scenario:
      required:
      - status
      - id
      - people
      - time
      type: object
      properties:
        id:
          type: integer
          format: int64
        time:
          type: integer
          format: int64
          default: 0
        status:
          type: string
          enum:
            - created
            - completed
          default: created
        people:
          type: array
          items:
            $ref: '#/components/schemas/Person'
      example:
        id: 45
        time: 0
        status: created
        people:
          - name: 'Jeff'
            x: 4
            y: 3
            status: alive
            items:
              - class: gun
                ammo: 2
              - class: knife
          - name: 'Fede'
            x: -1
            y: 5
            status: zombie
          - name: 'Bellini'
            x: 1
            y: 1
            status: zombie
          - name: 'Peluca'
            x: 0
            y: -2
            status: alive
            items:
              - class: gun
                ammo: 3
    CreateScenarioRequest:
      required:
      - id
      - people
      type: object
      properties:
        id:
          type: integer
          format: int64
        people:
          type: array
          items:
            $ref: '#/components/schemas/Person'
      example:
        id: 45
        people:
          - name: 'Jeff'
            x: 4
            y: 3
            status: alive
            items:
              - class: gun
                ammo: 2
              - class: knife
          - name: 'Fede'
            x: -1
            y: 5
            status: zombie
          - name: 'Bellini'
            x: 1
            y: 1
            status: zombie
          - name: 'Peluca'
            x: 0
            y: -2
            status: alive
            items:
              - class: gun
                ammo: 3
    RunScenarioRequest:
      required:
      - status
      type: object
      properties:
        status:
          type: string
          enum:
            - completed
          default: completed
      example:
        status: completed
